# app.py
"""Gradio interactive demo for AI-generated text detection.

Provides a web UI where users can paste text and see real-time
predictions from the ensemble model, along with linguistic feature
analysis and confidence visualization.

Run with:
    python app.py
"""

import os
import yaml

import gradio as gr
import numpy as np

from src.ensemble import EnsembleDetector
from src.features import extract_features


def _load_detector() -> EnsembleDetector:
    with open("configs/config.yaml", "r") as f:
        cfg = yaml.safe_load(f)
    return EnsembleDetector(
        baseline_path=os.path.join("models", "baseline", "tfidf_logreg.joblib"),
        transformer_dir=os.path.join("models", "transformer"),
        max_length=int(cfg["transformer"]["max_length"]),
    )


def analyze(text: str):
    """Run ensemble prediction and feature extraction."""
    if not text or not text.strip():
        return (
            {"Human-written": 0.5, "AI-generated": 0.5},
            "Please enter some text to analyze.",
            "",
        )

    result = detector.predict_single(text)
    features = extract_features(text)

    # Confidence output for Gradio Label component
    label_output = {
        "Human-written": result["prob_human"],
        "AI-generated": result["prob_ai"],
    }

    # Verdict text
    verdict = (
        f"**Prediction: {result['label_str']}** "
        f"(confidence: {result['confidence']:.1%})"
    )

    # Feature summary
    feat_lines = [
        f"| Feature | Value |",
        f"|---------|-------|",
        f"| Word count | {features['word_count']:.0f} |",
        f"| Vocabulary richness (TTR) | {features['ttr']:.3f} |",
        f"| Avg sentence length | {features['sent_len_mean']:.1f} words |",
        f"| Sentence length variation | {features['sent_len_std']:.1f} |",
        f"| Flesch Reading Ease | {features['flesch_reading_ease']:.1f} |",
        f"| Flesch-Kincaid Grade | {features['flesch_kincaid_grade']:.1f} |",
        f"| Word entropy | {features['word_entropy']:.2f} |",
        f"| Hapax legomena ratio | {features['hapax_ratio']:.3f} |",
        f"| Avg word length | {features['word_len_mean']:.1f} |",
    ]
    feat_md = "\n".join(feat_lines)

    return label_output, verdict, feat_md


# ---------------------------------------------------------------------------
# Build UI
# ---------------------------------------------------------------------------

detector = _load_detector()

with gr.Blocks(
    title="AI Text Detector",
    theme=gr.themes.Soft(),
) as demo:
    gr.Markdown(
        "# AI-Generated Text Detector\n"
        "Paste any text below to check whether it was written by a human or generated by AI.\n"
        "Uses an ensemble of **TF-IDF + Logistic Regression** and **fine-tuned DistilBERT**."
    )

    with gr.Row():
        with gr.Column(scale=2):
            text_input = gr.Textbox(
                label="Input Text",
                placeholder="Paste or type text here...",
                lines=10,
            )
            analyze_btn = gr.Button("Analyze", variant="primary")

        with gr.Column(scale=1):
            label_output = gr.Label(label="Classification", num_top_classes=2)
            verdict_output = gr.Markdown(label="Verdict")

    feat_output = gr.Markdown(label="Linguistic Features")

    analyze_btn.click(
        fn=analyze,
        inputs=[text_input],
        outputs=[label_output, verdict_output, feat_output],
    )

    gr.Examples(
        examples=[
            ["The quick brown fox jumps over the lazy dog. This is a simple sentence written by a human to test the detector."],
            ["In the realm of artificial intelligence, natural language processing has emerged as a transformative technology that enables machines to understand, interpret, and generate human language with unprecedented accuracy and sophistication."],
        ],
        inputs=[text_input],
    )

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860, share=False)
